-- Initial schema, matching the v1 entities (Product, Order, OrderItem).
-- Hibernate runs with ddl-auto=validate, so column types must match the entity mappings:
-- enums are plain VARCHAR (not H2 ENUM, see HHH-17675) and LocalDateTime is TIMESTAMP(6).

CREATE TABLE products (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255)   NOT NULL,
    sku         VARCHAR(64)    NOT NULL,
    description VARCHAR(1000),
    price       NUMERIC(12, 2) NOT NULL,
    quantity    INTEGER        NOT NULL,
    created_at  TIMESTAMP(6),
    updated_at  TIMESTAMP(6),
    version     BIGINT,
    CONSTRAINT uk_products_sku UNIQUE (sku)
);

-- "order" is a reserved word, hence "orders".
CREATE TABLE orders (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status       VARCHAR(20)    NOT NULL,
    total_amount NUMERIC(14, 2),
    created_at   TIMESTAMP(6),
    updated_at   TIMESTAMP(6)
);

CREATE TABLE order_items (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id       BIGINT,
    product_id     BIGINT,
    quantity       INTEGER NOT NULL,
    price_per_unit NUMERIC(12, 2),
    subtotal       NUMERIC(14, 2),
    CONSTRAINT fk_order_items_order FOREIGN KEY (order_id) REFERENCES orders (id),
    CONSTRAINT fk_order_items_product FOREIGN KEY (product_id) REFERENCES products (id)
);

CREATE INDEX idx_order_items_order ON order_items (order_id);
CREATE INDEX idx_order_items_product ON order_items (product_id);
