-- Stock ledger (StockMovement). Same type rules as V1: reason is plain VARCHAR, created_at is TIMESTAMP(6).
-- order_id, purchase_order_id and location_id have no foreign keys on purpose: pending orders can be deleted
-- while their movements stay, and the purchase_orders and locations tables don't exist yet.

CREATE TABLE stock_movements (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id        BIGINT       NOT NULL,
    delta             INTEGER      NOT NULL,
    reason            VARCHAR(20)  NOT NULL,
    note              VARCHAR(500),
    order_id          BIGINT,
    purchase_order_id BIGINT,
    location_id       BIGINT,
    created_at        TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_stock_movements_product FOREIGN KEY (product_id) REFERENCES products (id),
    CONSTRAINT ck_stock_movements_delta CHECK (delta <> 0)
);

CREATE INDEX idx_stock_movements_product ON stock_movements (product_id);
CREATE INDEX idx_stock_movements_created_at ON stock_movements (created_at);

-- Products that already exist get an opening balance, so each product's movements add up to its quantity.
INSERT INTO stock_movements (product_id, delta, reason, note, created_at)
SELECT id, quantity, 'ADJUSTMENT', 'Opening balance', LOCALTIMESTAMP
FROM products
WHERE quantity <> 0;
